### ISSUE TITLE
2.0.0 Release Plan

### ISSUE THREAD

**Issue by braxtonhall** [braxtonhall/library-thing#240]
- [ ] Get OAuth Flow verified by Google #217
- [ ] Close remaining 2.0.0 feature ticket #238
- [ ] Merge what we have so far in terms of documentation #228 
- [ ] Release a `1.3.*` release on Chrome/Firefox
  - We do this _before_ releasing `2.0.0` so we have placeholder in the store at the time the patch notes are released
- [ ] Get extension verified by Chrome/Firefox
- [ ] Bump version and push 2.0.0 tag
  - We do this _after_ releasing `1.3.*` so we have a placeholder in the store at the time the patch notes are released
- [ ] Release a `2.0.0` release on Chrome/Firefox
- [ ] Update all of our documentation with help from someone better at writing documentation
